---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bezuide3/zs1gwl.co.za/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R demo $DEPLOYPATH
    - /bin/cp *.* $DEPLOYPATH
    